apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: alerts-feedback
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | trim | indent 4 }}
{{- end }}
spec:
  backend:
    serviceName: {{ .Values.service.name }}
    servicePort: {{ .Values.service.port }}
  rules:
  - host: alerts-feedback.{{ .Values.ingress.dnsZone }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
  - host: alerts-feedback.{{ .Values.ingress.rootDnsZone }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
